# Generated by Django 4.0.3 on 2022-04-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='likes',
            field=models.BooleanField(default=False),
        ),
    ]
